### ISSUE TITLE
PHP types are not type hints but type declarations

### ISSUE THREAD

**Issue by Girgias** [florentpoujol/php8-type-system#1]
PHP enforces types at runtime so they are not hints but actual proper declarations.

The PHP manual also refers to them as type declarations.

**Comment by florentpoujol** [comment]
I agree with the term "type declaration" of course, but don't we call them "typehint" all the time ?

At least in userland space I have the feeling we always use "typehint" instead of "type declaration".

And personally that is what I have always ever called them.

**Comment by florentpoujol** [comment]
This is now done, I replaced all usages of "typehint" to "type declaration", thanks for your input.
